BoundaryConditions:
  Hydro_Right_Boundary: r  
  Rad_Left_Boundary: v
  Rad_Right_Boundary: r 
  Rad_Dirichlet_Left: 0
  Rad_Dirichlet_Right: 0
  Rad_Source_Right: 0
  Rad_Source_Left: 0
FixedParameters:
  nx: 172 
  ng: 25
  np: 1
  RadNg: 30
  MaxE: 30
  FixedOpacityValue: 0
  Frontheat_LastIndex: 0
  Frontheat_StartIndex: 0
  Output_Frequency: 500
  Preheat_LastIndex: 0
  Preheat_StartIndex: 0
  leakMaterial: 1
  leakArea1: 1.0  
  leakArea2: 1.0
LaserParams:
  Duration: 1.0e-9 
  Constant_Power: 5.0E18 #If load in laser profile is true this is ignored.
  Wavelength: 0.351e-6 
  Angle: 0
  Albedo: 0
  CriticalLeak: 0.0
  CriticalDumpFraction: 1.0
  StartIndex: 172 
Limiters:
  heatflxlmE: 0.15 
  heatflxlmI: 0.15
  prrm1: 1.0
  prrm2: 1.0  
  radabm: 1.0
  radbrm: 1.0
  radcmm: 1.0
  raddfm: 1.0
  radesm: 1.0
  radflxlm: 1.0
  larsen: 2.0
  sphecamE1: 1.0  
  sphecamI1: 1.0 
  opamP1: 1.0
  opamR1: 1.0  
  sphecamE2: 1.0 
  sphecamI2: 1.0 
  opamP2: 1.0
  opamR2: 1.0
Output:
  Coordinates: true
  CreateOutputFolder: true
  Exchange: true
  HeatFlow: true
  InternalEnergy: true
  InverseBrem: true
  MassDensity: true
  NumberDensity: true
  PlasmaParameters: true 
  Pressure: true
  RadEnergyDensity: true
  RadFreeFree: true
  RadMultiGroupEnergy: true
  RadTemperature: true
  Temperature: true
  ThermalConduction: true
  Velocity: true 
  Viscosity: true
  Zbar: true
Paths:
  FEOS_Path_1: 
  FEOS_Path_2: 
  Opacity_Path_1:  
  Opacity_Path_2: 
  Laser_Profile_Path: 
  Leak_Profile_Path: 
  Init_Path: 
  Out_Path: 
Switches:
   AdapativeTimeStep: true
   AdiabaticMode: false
   ConstantCoulombLog: false
   CoupleDivQ: false
   CoupleMulti: false
   CoupleOperatorSplit: false
   CoupleSubtract: false
   EoSTables: true 
   Exchange: true
   FullyIonized: false
   HeatConduction: false
   IdealGas: false
   ImplicitHeatConduction: false
   InvBrem: true
   IonizationTables: true
   IsothermalMode: false
   LeakSource: false
   LoadInLaserProfile: true
   LoadInRadEnergy: false
   MultiMaterial: true
   RadDiffusion: true
   RadFreeFree: true
   RadiationTransport: true
   SNBHeatFlow: true
   LeeMore: false
   SingleTemperature: false
   Velocity: true
   Viscosity: true
TimeParameters:
   AdapativeMethod: 0
   ElectronLimit: 0.04
   IonLimit: 0.02
   PVLimit: 0.05
   RadLimit: 0.02
   VolLimit: 0.01
   cfl: 0.85
   dt: 1.0e-17
   dt_max: 1.0e-12
   dt_min: 1.0e-19
   steps: 0 
   t_init: 0.0e-9
   t_max: 1.0e-9  
